name: build-and-bump-dev
on:
  push:
    branches: ["master","main"]
  workflow_dispatch: {}

jobs:
  build-publish-bump:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/cliu701/podinfo
      TAG: ${{ github.sha }}
      ENV_REPO: cliu701/env-repo-podinfo
      DEV_KUSTOMIZE_PATH: apps/podinfo/overlays/dev
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR (with GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image (multi-arch)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t "$IMAGE:$TAG" \
            --push .

      - name: Bump env repo (update newTag only)
        env:
          GH_PAT: ${{ secrets.ENV_REPO_PAT }}
        run: |
          set -e
          git config --global user.name "ci-bot"
          git config --global user.email "bot@cliu701"
          git clone "https://cliu701:${GH_PAT}@github.com/${ENV_REPO}.git" env
          cd "env/${DEV_KUSTOMIZE_PATH}"
          sed -i 's#newTag:.*#newTag: "'"${TAG}"'"#' kustomization.yaml
          git add -A
          git commit -m "dev: deploy ${IMAGE}:${TAG} from ${GITHUB_SHA}" || echo "No changes"
          git push origin main
